import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";

import { Providers } from "@/provider/providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: "%s | FanOfAction",
    default: "FanOfAction",
  },
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ABB7C4" },
    { media: "(prefers-color-scheme: dark)", color: "#102132" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
