export { LogoIcon } from "./logo";
export { PlayIcon } from "./play-icon";
export { InstagramIcon } from "./instagram-icon";
export { FacebookIcon } from "./facebook-icon";
export { YoutubeIcon } from "./youtube-icon";
export { DesktopIcon } from "./desktop-icon";
export { SunIcon } from "./sun-icon";
export { MoonIcon } from "./moon-icon";
export { MovieIcon } from "./movie-icon";
export { MapIcon } from "./map-icon";
export { ArrowDownIcon } from "./arrow-down-icon";
export { FacebookCircleIcon } from "./facebook-circle-icon";
export { TwitterCircleIcon } from "./twitter-circle-icon";
export { InstagramCircleIcon } from "./instagram-circle-icon";
export { ChevronBackwardIcon } from "./chevron-backward-icon";
export { SearchIcon } from "./search-icon";
export { TrendingIcon } from "./trending-icon";
export { MoreInfoIcon } from "./more-info-icon";
export { GetLocationIcon } from "./get-location-icon";
export { ReReleaseIcon } from "./re-release-icon";
export { RecommendationIcon } from "./recommendation-icon";
export { ReviewIcon } from "./review-icon";
export { ArrowRightIcon } from "./arrow-right-icon";
export { TicketIcon } from "./ticket-icon";
export { DialogCloseIcon } from "./dialog-close-icon";

import type { IconProps } from "./types";

export type IconElement = React.ComponentType<IconProps>;
export { IconProps };
